FROM {{ jupyter.base_image }}:{{ jupyter.base_image_version }}

USER root

RUN apt-get update \
    && apt-get install -yq --no-install-recommends \
        apt-utils \
        curl \
        pkg-config \
        software-properties-common \
    && LANG=C.UTF-8 add-apt-repository -y ppa:ubuntugis/ppa \
    && apt update

USER jovyan

RUN pip3 install psycopg2-binary
RUN pip3 install pika


